version: '3.8'

services:
  app:
    container_name: amplizard_ecom_test
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "6060:6060"
    environment:
      - PORT=6060

    command: sh -c "cd /app && npm install && node server.js"
